import { q } from '../../src/lib/content/plan';

// Timed halfway checkpoints for the A+ modules: exam-style questions across each module.

export const core1 = {
  mobile: [
    q.single('A technician must add memory to a thin laptop. Which module type should they buy?', ['DIMM', 'SO-DIMM', 'M.2', 'SIMM'], 1, 'Laptops use SO-DIMMs.'),
    q.single('Which short-range technology is used for contactless payments?', ['Bluetooth', 'NFC', 'Infrared', '802.11ac'], 1),
    q.single('A company wants to remotely wipe lost phones and force a PIN on all devices. What does it need?', ['A VPN', 'MDM', 'A KVM switch', 'DHCP'], 1),
    q.tf('Tethering shares a phone’s cellular connection with another device.', true),
    q.single('Which connects a laptop to monitors, a keyboard and a wired network through one connector?', ['Docking station', 'Stylus', 'Smart card reader', 'Toner probe'], 0),
    q.multi('Which are mobile device synchronisation methods?', ['Cloud account sync', 'USB sync to a computer', 'Using a crossover cable', 'Bluetooth to a printer'], [0, 1]),
    q.single('Airplane mode is turned on. What still works without re-enabling anything?', ['Cellular calls', 'Offline apps', 'Wi-Fi', 'Bluetooth'], 1),
    q.single('Which helps locate a lost phone on a map?', ['GPS-based location services', 'An SO-DIMM', 'Screen lock', 'Airplane mode'], 0),
  ],
  networking: [
    q.match('Match the port to the service.', [['25', 'SMTP'], ['53', 'DNS'], ['3389', 'RDP'], ['443', 'HTTPS']]),
    q.single('A PC has the address 169.254.33.7. What is the most likely cause?', ['DNS failure', 'No DHCP server reached', 'Static IP set', 'Duplicate MAC'], 1),
    q.single('Which DNS record lets mail servers check that a message wasn’t altered by verifying a signature?', ['SPF', 'DKIM', 'MX', 'AAAA'], 1),
    q.single('Which device connects different networks and makes forwarding decisions using IP addresses?', ['Switch', 'Hub', 'Router', 'Access point'], 2),
    q.single('Which is a private IPv4 address?', ['192.168.10.5', '8.8.8.8', '1.1.1.1', '100.200.1.1'], 0),
    q.single('Which internet connection usually has the highest latency?', ['Fibre', 'Cable', 'Geostationary satellite', 'DSL'], 2),
    q.single('Which tool locates a cable at a patch panel by following an audible tone?', ['Crimper', 'Toner probe', 'Punchdown', 'Loopback plug'], 1),
    q.tf('UDP retransmits lost packets automatically.', false, 'UDP has no acknowledgements; TCP does.'),
    q.single('Which separates a single switch into isolated logical networks?', ['VPN', 'VLAN', 'NAT', 'QoS'], 1),
    q.single('Which Wi-Fi band generally travels furthest through walls?', ['2.4 GHz', '5 GHz', '6 GHz', '60 GHz'], 0),
  ],
  hardware1: [
    q.single('Which cable should be used above a drop ceiling used for air return?', ['PVC', 'Plenum', 'Direct burial', 'Coax'], 1),
    q.order('Put T568B pins 1–4 in order.', ['White/orange', 'Orange', 'White/green', 'Blue']),
    q.single('Which fibre type is best for a 10 km link between buildings?', ['Multimode', 'Single-mode', 'Cat 6a', 'Coax'], 1),
    q.single('Which video connector does NOT carry audio?', ['HDMI', 'DisplayPort', 'VGA', 'USB-C (DP Alt Mode)'], 2),
    q.single('Which memory type detects and corrects single-bit errors?', ['ECC', 'Non-ECC', 'SODIMM', 'Virtual memory'], 0),
    q.single('Four 4 TB disks in RAID 10 give how much usable space?', ['4 TB', '8 TB', '12 TB', '16 TB'], 1, 'RAID 10 mirrors, so half the raw capacity.'),
    q.single('Which storage is fastest for an OS drive?', ['5400 rpm HDD', 'NVMe SSD', 'USB 2.0 flash', 'Optical disc'], 1),
    q.tf('A display’s native resolution gives the sharpest picture.', true),
    q.single('Which connector is used for telephone lines and DSL?', ['RJ45', 'RJ11', 'LC', 'BNC'], 1),
    q.num('What is the maximum length in metres of a standard copper Ethernet run?', 100, 0),
  ],
  hardware2: [
    q.single('A user wants to run VMs but gets an error that virtualization isn’t available. Where should you look?', ['BIOS/UEFI settings', 'Printer properties', 'DNS settings', 'Display settings'], 0),
    q.single('Which motherboard component stores keys used by BitLocker?', ['TPM', 'CMOS battery', 'PCIe slot', 'Chipset fan'], 0),
    q.order('Put the laser printing process in order.', ['Processing', 'Charging', 'Exposing', 'Developing', 'Transferring', 'Fusing', 'Cleaning']),
    q.single('Printed pages smudge when touched. Which part is most likely failing?', ['Fuser', 'Pickup roller', 'Transfer belt', 'Network card'], 0),
    q.single('Which slot is usually used for a high-end graphics card?', ['PCIe x1', 'PCIe x16', 'M.2 B-key', 'SATA'], 1),
    q.single('Which power rail supplies most of the power to CPUs and GPUs?', ['+3.3 V', '+5 V', '+12 V', '−12 V'], 2),
    q.single('Which printer type is best for multi-part carbon forms?', ['Laser', 'Inkjet', 'Impact', 'Thermal'], 2),
    q.single('Which UEFI feature blocks unsigned boot loaders?', ['Secure Boot', 'Fast Boot', 'Wake-on-LAN', 'XMP'], 0),
    q.tf('Thermal printers need ink cartridges.', false, 'They use heat-sensitive paper.'),
    q.single('A new CPU doesn’t fit the motherboard. What was not checked?', ['Socket compatibility', 'RAM colour', 'Case size', 'Monitor cable'], 0),
  ],
  cloud: [
    q.single('Which hypervisor runs directly on the hardware?', ['Type 1', 'Type 2', 'Container engine', 'Browser'], 0),
    q.match('Match each cloud model to an example.', [['SaaS', 'Web email'], ['PaaS', 'App hosting platform'], ['IaaS', 'Rented virtual servers']]),
    q.single('Automatically scaling resources up and down with demand is…', ['Elasticity', 'Redundancy', 'Tenancy', 'Shared resources'], 0),
    q.order('Put the troubleshooting steps in order.', ['Identify the problem', 'Establish a theory of probable cause', 'Test the theory', 'Establish a plan of action and implement it', 'Verify full system functionality', 'Document findings']),
    q.single('A drive clicks and SMART reports reallocated sectors. What first?', ['Back up the data now', 'Defragment it', 'Ignore it', 'Format it'], 0),
    q.single('Users can reach sites by IP but not by name. What is the likely problem?', ['DNS', 'DHCP', 'Cabling', 'Printer driver'], 0),
    q.single('A laptop battery is swollen. What should you do?', ['Stop using it and replace it', 'Charge it overnight', 'Press it back into place', 'Update the BIOS'], 0),
    q.single('Print jobs pile up in the queue and nothing prints. What do you restart?', ['Print Spooler service', 'DNS client', 'Explorer', 'Windows Update'], 0),
    q.tf('Containers share the host operating system’s kernel.', true),
    q.single('A monitor shows "No signal" after a move. What do you check first?', ['Cable and input source', 'RAM seating', 'CPU paste', 'BIOS password'], 0),
  ],
};

export const core2 = {
  os1: [
    q.single('A user needs to store a 6 GB file on a USB stick used on Windows and macOS. Which file system?', ['FAT32', 'exFAT', 'NTFS', 'ext4'], 1),
    q.single('Which partition style is required for UEFI boot on drives over 2 TB?', ['MBR', 'GPT', 'FAT', 'Dynamic'], 1),
    q.single('Which Windows edition can’t join a domain?', ['Home', 'Pro', 'Enterprise', 'Education'], 0),
    q.single('Which tool shows logs of system errors?', ['Event Viewer', 'Disk Cleanup', 'Paint', 'Calculator'], 0),
    q.single('Which command repairs protected system files?', ['sfc /scannow', 'gpupdate', 'net use', 'tracert'], 0),
    q.single('Which command shows each hop to a destination?', ['tracert', 'ipconfig', 'hostname', 'netstat'], 0),
    q.single('A program should start at sign-in only when needed. Where do you disable it?', ['Task Manager → Startup apps', 'Device Manager', 'Regedit always', 'Disk Management'], 0),
    q.single('Which MMC snap-in updates or rolls back a driver?', ['Device Manager', 'Event Viewer', 'Task Scheduler', 'Certificate Manager'], 0),
    q.tf('An in-place upgrade keeps user files and applications.', true),
    q.single('Users can’t see file extensions. Where do you fix it?', ['File Explorer Options', 'Power Options', 'Sound', 'Mouse'], 0),
  ],
  os2: [
    q.single('Which Windows Firewall profile should apply on public Wi-Fi?', ['Domain', 'Private', 'Public', 'Off'], 2),
    q.single('Which command maps drive Z: to a network share?', ['net use Z: \\\\server\\share', 'ipconfig Z:', 'map Z:', 'format Z:'], 0),
    q.match('Match the macOS tool to the Windows equivalent.', [['Activity Monitor', 'Task Manager'], ['Finder', 'File Explorer'], ['Terminal', 'Command Prompt'], ['Time Machine', 'File History']]),
    q.single('Which Linux command shows disk free space?', ['df -h', 'ls', 'pwd', 'chmod'], 0),
    q.single('Which Linux command runs a command with administrator rights?', ['sudo', 'chown', 'grep', 'man'], 0),
    q.single('Which Linux directory holds configuration files?', ['/etc', '/var/log', '/home', '/tmp'], 0),
    q.single('Which macOS feature encrypts the startup disk?', ['FileVault', 'Spotlight', 'Dock', 'Keychain'], 0),
    q.tf('A 64-bit application can’t run on a 32-bit operating system.', true),
    q.single('Which marks a Wi-Fi network so Windows limits background downloads?', ['Metered connection', 'Proxy', 'VPN', 'Static IP'], 0),
    q.single('Before installing an app, what do you check first?', ['System requirements', 'Desktop theme', 'Mouse speed', 'Printer toner'], 0),
  ],
  security1: [
    q.single('A secure entry with two doors where only one opens at a time is…', ['Access control vestibule', 'Bollard', 'Badge', 'Guard dog'], 0),
    q.single('Password plus fingerprint is…', ['Single-factor', 'Multi-factor', 'SSO', 'Federation'], 1),
    q.single('Which AD feature applies settings to many PCs?', ['Group Policy', 'Disk Management', 'Task Manager', 'Event Viewer'], 0),
    q.single('Which Wi-Fi security is strongest?', ['WEP', 'WPA', 'WPA2', 'WPA3'], 3),
    q.single('Which malware locks files and demands payment?', ['Ransomware', 'Spyware', 'Adware', 'Worm'], 0),
    q.single('Which malware spreads across networks on its own?', ['Worm', 'Trojan', 'Rootkit', 'Keylogger'], 0),
    q.single('Which gives users only the permissions they need?', ['Least privilege', 'Implicit allow', 'Shared accounts', 'Admin by default'], 0),
    q.single('Which uses a RADIUS server to authenticate each Wi-Fi user?', ['WPA2/3-Enterprise', 'WPA2-Personal', 'Open', 'WPS'], 0),
    q.tf('UAC prompts before changes that need administrator rights.', true),
    q.single('Which Windows feature encrypts removable drives?', ['BitLocker To Go', 'EFS only', 'Defender', 'OneDrive'], 0),
  ],
  security2: [
    q.order('Put the malware removal steps in order.', ['Investigate and verify symptoms', 'Quarantine the infected system', 'Disable System Restore (Windows)', 'Remediate: update tools and scan', 'Schedule scans and run updates', 'Re-enable System Restore and create a restore point', 'Educate the end user']),
    q.single('A caller pretends to be from IT and asks for a password. This is…', ['Vishing / impersonation', 'Tailgating', 'Worm', 'Brute force'], 0),
    q.single('Input of \' OR 1=1 -- into a login form tests for…', ['SQL injection', 'XSS', 'DoS', 'ARP poisoning'], 0),
    q.single('An attacker inserts script into a web page that runs in other users’ browsers. This is…', ['Cross-site scripting', 'SQL injection', 'Phishing', 'Smishing'], 0),
    q.single('Which best stops someone using a stolen password?', ['MFA', 'Longer screen timeout', 'A bigger monitor', 'Disabling logs'], 0),
    q.single('Which physically destroys data on old drives?', ['Shredding', 'Quick format', 'Recycle bin', 'Defrag'], 0),
    q.multi('Which harden a SOHO router?', ['Change default admin password', 'Update firmware', 'Disable WPS', 'Leave remote admin on'], [0, 1, 2]),
    q.single('A browser warns about an invalid certificate on a banking site. What should the user do?', ['Stop and report it', 'Click through', 'Save the password', 'Turn off HTTPS'], 0),
    q.single('A request to change supplier bank details arrives by email. What do you do?', ['Verify by phone using a known number', 'Change it immediately', 'Reply asking if it’s real', 'Forward to all staff'], 0),
    q.tf('Remote wipe protects data on a lost mobile device.', true),
  ],
  operations: [
    q.single('Windows blue-screens after a driver update. First step?', ['Safe Mode and roll back the driver', 'Replace RAM', 'Reinstall Windows', 'Disable the firewall'], 0),
    q.single('Which records who handled evidence?', ['Chain of custody', 'SLA', 'AUP', 'Asset tag'], 0),
    q.single('3-2-1 backups means…', ['3 copies, 2 media, 1 off-site', '3 backups a day', '3 servers, 2 sites, 1 cloud', '3 disks, 2 tapes, 1 USB'], 0),
    q.single('Which document explains how to handle a hazardous chemical?', ['SDS', 'AUP', 'SLA', 'NDA'], 0),
    q.single('Which file extension is a PowerShell script?', ['.ps1', '.sh', '.bat', '.js'], 0),
    q.single('A change goes wrong in production. What should already exist?', ['A rollback plan', 'A new wallpaper', 'A bigger budget', 'Nothing'], 0),
    q.single('Which protects components when handling them?', ['ESD strap', 'Wool gloves', 'Carpet', 'Magnet'], 0),
    q.single('Which is the most secure remote admin method for Linux?', ['SSH with keys', 'Telnet', 'FTP', 'RDP over the internet'], 0),
    q.tf('You should check AI-generated answers before relying on them.', true),
    q.single('A phone shows unknown apps and heavy data use. What is likely?', ['Malware', 'A cracked screen', 'Full storage', 'A bad charger'], 0),
  ],
};
